In [6]:
import numpy as np

In [ ]:
#1D array
array=np.array([0,1,2])
shape=array.shape
print(shape)

(3,)


In [14]:
type(array)

numpy.ndarray

In [22]:
#list to array
y=[1,2,3]
array=np.array(y)
y


[1, 2, 3]

In [15]:
print(type(y))

<class 'list'>


In [25]:
a=np.array([1,2,3])
print(a)
a
type(a)
shape=a.shape
print(shape)
print(type(a))

[1 2 3]
(3,)
<class 'numpy.ndarray'>


In [24]:
x=[1,2,3]
y=np.array(x)
y

array([1, 2, 3])

In [29]:
l=[]
for i in range(10):
    l.append(i)
print(l)
print(type(l))
        

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
<class 'list'>


In [32]:
l=[]
for i in range(1,10):
    
    b=np.array(l)
    l.append(i)
    print(b)

[]
[1]
[1 2]
[1 2 3]
[1 2 3 4]
[1 2 3 4 5]
[1 2 3 4 5 6]
[1 2 3 4 5 6 7]
[1 2 3 4 5 6 7 8]


In [ ]:
#inside loop
l=[]
for i in range(1,5):
    a=int(input("enter a number:"))
    l.append(a)
    print(np.array(l))
    shape=np.shape(l)
    print(shape)

[5]
(1,)
[5 5]
(2,)
[5 5 5]
(3,)
[5 5 5 5]
(4,)


In [ ]:
#outside loop
l=[]
for i in range(1,5):
    a=int(input("enter a number:"))
    l.append(a)
print(np.array(l))
shape=np.shape(l)
print(shape)

[1 1 3 4]
(4,)
