In [4]:
import numpy as np

In [9]:
#1-D array
array=np.array([1,2,3])
print(array)
shape=np.shape(array)
print(shape)
print(array.ndim)

[1 2 3]
(3,)
1


In [11]:
#2-D array
array=np.array([[1,2,3]])
print(array)
shape=np.shape(array)
print(shape)
print(array.ndim)

[[1 2 3]]
(1, 3)
2


In [12]:
#3-D array
array=np.array([[[1,2,3]]])
print(array)
shape=np.shape(array)
print(shape)
print(array.ndim)

[[[1 2 3]]]
(1, 1, 3)
3


In [16]:
arr1=np.array([[1,2,3],[4,5,6]])
print(arr1)
print(arr1.ndim)

[[1 2 3]
 [4 5 6]]
2


In [ ]:
#NumPy requires equal-length rows so it can create a proper table (array) with a fixed shape
arr2=np.array([[1,2,3],[1,2,3,4]])
print(arr2)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [28]:
arr3=np.array([[[1,2,3],[1,2,3],[1,2,3]]])
print(arr3)
print(arr3.ndim)

[[[1 2 3]
  [1 2 3]
  [1 2 3]]]
3


In [34]:
arr4=np.array([1,2,3], ndmin=5)
print(arr4)
print(arr4.ndim)

[[[[[1 2 3]]]]]
5
