In [1]:
import numpy as np

In [ ]:
#zeros
arr_zero=np.zeros(4)
print(arr_zero)

[0. 0. 0. 0.]


In [6]:
arr_0=np.zeros((3,4))
print(arr_0)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
#ones
arr_one=np.ones(5)
print(arr_one)

[1. 1. 1. 1. 1.]


In [8]:
arr_1=np.ones((4,5))
print(arr_1)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
#empty array
arr_em=np.empty(4)
print(arr_em)

[0. 0. 0. 0.]


In [12]:
#range array
arr_rn=np.arange(4)
print(arr_rn)

[0 1 2 3]


In [13]:
arr_rn=np.arange(1,5)
print(arr_rn)

[1 2 3 4]


In [14]:
#diagonal
arr_dia=np.eye(3)
print(arr_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
arr_dia=np.eye(3)
print(arr_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [24]:
#linspace function
arr_lin=np.linspace(1,10,num=5)
print(arr_lin)

[ 1.    3.25  5.5   7.75 10.  ]
