In [1]:
import numpy as np

rand():the function is used to generate a random value between 0 and 1 

randn():the function is used to generate a random value close to zero, this may return positive and negitive values as well

ranf():the function for doing random sampling in numpy.it returns array of specified shapes and fills it with random floats in the half open interval[0.0,1.1)

randint():the function is used to generate a random number between a range

rand()

In [2]:
import numpy as np
a=np.random.rand(4)
print(a)

[0.14332716 0.34876643 0.84781996 0.70223134]


In [3]:
a_1=np.random.rand(2,4)
print(a_1)

[[0.24455038 0.4695128  0.62957517 0.73474881]
 [0.76670653 0.76210337 0.14007337 0.98705571]]


In [4]:
b=np.random.randn(3)
print(b)

[ 0.81478264 -1.95851265 -0.21103728]


In [5]:
b_1=np.random.randn(4,5)
print(b_1)

[[ 1.72764021  1.00657262 -0.10651879  0.22296988  0.26251304]
 [ 1.41926135 -1.55951841  1.3797057   0.64984996 -0.64800308]
 [ 0.01942173  0.61067405  0.30073552 -0.13824756 -0.4183052 ]
 [-0.00705121  0.13112073  0.26364326 -0.19674635  0.73171808]]


In [6]:
c=np.random.ranf(4)
print(c)

[0.18471816 0.28877916 0.13036646 0.58060039]


In [13]:
c_1=np.random.ranf(3)
print(c_1)

[0.32348057 0.11296553 0.36463637]


randint()
d=np.random.randint(min,max,total_values)

In [17]:
d=np.random.randint(3,100,5)
print(d)

[11 22 64 59 61]
