Shape

In [5]:
import numpy as np
arr=np.array([[1,2,3,],[3,4,5]])
print(arr)
print(arr.shape)

[[1 2 3]
 [3 4 5]]
(2, 3)


In [7]:
arr_1=np.array([[1,2,3,4],[5,6,7,8]],ndmin=5)
print(arr_1)
print(arr_1.ndim)
print(arr_1.shape)

[[[[[1 2 3 4]
    [5 6 7 8]]]]]
5
(1, 1, 1, 2, 4)


Reshape

arr_2=np.array([1,2,34,5,6])
x=arr_2(reshape(2,3))

In [15]:
arr_2=np.array([1,2,3,4,5,6])
x=arr_2.reshape(3,2)
print(x)
print(arr_2.ndim)
print(x.ndim)

[[1 2]
 [3 4]
 [5 6]]
1
2


In [19]:
arr_3=np.array([1,2,3,4,5,6,1,6,9])
x=arr_3.reshape(3,3)
print(x)
print(arr_3.ndim)
print(x.ndim)

[[1 2 3]
 [4 5 6]
 [1 6 9]]
1
2


In [28]:
arr_3=np.array([1,2,3,4,5,6,1,6,9,20,45,10,2,5,8,15,7,8])
x=arr_3.reshape(3,3,2)
print(x)
print(arr_3.ndim)
print(x.ndim)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 1  6]
  [ 9 20]
  [45 10]]

 [[ 2  5]
  [ 8 15]
  [ 7  8]]]
1
3


In [36]:
arr_4=np.random.randint(1,15,8)
print(arr_4)
x=arr_4.reshape(2,2,2)
print(x)
print(x.ndim)

[ 6 11  9 10  7  1  6  5]
[[[ 6 11]
  [ 9 10]]

 [[ 7  1]
  [ 6  5]]]
3


In [37]:
arr_3=np.array([1,2,3,4,5,6,1,6,9,20,45,10,2,5,8,15,7,8])
x=arr_3.reshape(3,3,2)
print(x)
print(arr_3.ndim)
print(x.ndim)
print()
x_1=x.reshape(-1)
print(x_1)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 1  6]
  [ 9 20]
  [45 10]]

 [[ 2  5]
  [ 8 15]
  [ 7  8]]]
1
3

[ 1  2  3  4  5  6  1  6  9 20 45 10  2  5  8 15  7  8]
