In [1]:
import numpy as np

Arithmetic operations in numpy arrays
a+b-np.add(a,b)
a-b-np.subtract(a,b)
a*b-np.multiply(a,b)
a/b-np.divide(a,b)
a%b-np.mod(a,b)
a**b-np.power(a,b)
1/a-np.reciprocal(a)


In [30]:
var1=np.array([1,2,3,4])
varadd=var1+3
print(varadd)
varadd=np.add(var1,3)
print(varadd)



[4 5 6 7]
[4 5 6 7]


In [31]:
var1=np.array([4,5,6,7])
var2=np.array([10,40,36,72])
varadd=var1+var2
print(varadd)
varadd=np.add(var1,var2)
print(varadd)

[14 45 42 79]
[14 45 42 79]


In [41]:
var1=np.array([4,6,8,4])
varsub=var1-3
print(varsub)
varsub=np.subtract(var1,3)
print(varsub)


[1 3 5 1]
[1 3 5 1]


In [ ]:
var1=np.array([2,7,4,9])
var2=np.array([3,6,4,8])
varsub=var1-var2 
print(varsub)


[-1  1  0  1]


In [43]:
var1=np.array([4,6,8,4])
varmultiply=var1*3
print(varmultiply)
varmultiply=np.multiply(var1,3)
print(varmultiply)

[12 18 24 12]
[12 18 24 12]


In [8]:
var1=np.array([2,7,4,9])
var2=np.array([3,6,4,8])
varmultiply=var1*var2 
print(varmultiply)

[ 6 42 16 72]


In [19]:
var1=np.array([4,6,8,4])
vardivide=var1/3
print(vardivide)
print(np.round(vardivide,2))


[1.33333333 2.         2.66666667 1.33333333]
[1.33 2.   2.67 1.33]


In [20]:
var1=np.array([2,7,4,9])
var2=np.array([3,6,4,8])
vardivide=var1/var2 
print(vardivide)
print(np.round(vardivide,2))

[0.66666667 1.16666667 1.         1.125     ]
[0.67 1.17 1.   1.12]


In [21]:
var1=np.array([4,6,8,4])
varmod=var1%3
print(varmod)

[1 0 2 1]


In [22]:
var1=np.array([2,7,4,9])
var2=np.array([3,6,4,8])
varmod=var1%var2 
print(varmod)

[2 1 0 1]


In [23]:
var1=np.array([4,6,8,4])
varexp=var1**2
print(varexp)

[16 36 64 16]


In [ ]:
var1=np.array([2,7,4,9])
var2=np.array([3,6,4,8])
varexp=var1**var2 
print(varexp)

[       8   117649      256 43046721]


In [25]:
var1=np.array([4,6,8,4])
varreci=1/var1
print(varreci)

[0.25       0.16666667 0.125      0.25      ]


In [46]:
var1=np.array([4,6,8,4])
varreci=np.reciprocal(var1)
print(varreci)

[0 0 0 0]


In [ ]:
var1=np.array([2,7,4,9])
var2=np.array([3,6,4,8])
varexp=var1**var2 
print(varexp)

2D array

In [45]:
var21=np.array([[1,2,4],[3,5,2]])
var22=np.array([[1,2,4],[3,5,2]])
var=np.add(var21,var22)
print(var)

[[ 2  4  8]
 [ 6 10  4]]
