In [1]:
import numpy as np

Arithmetic functions
np.min(x)
np.max(x)
np.argmin(x)
np.argmax(x)
np.sqrt(x)
np.sin(x)
np.cos(x)
np.cumsum(x)


MIN

In [3]:
var=np.array([1,2,3,4,5,6,7])
print(np.min(var))

1


MAX

In [27]:
var=np.array([1,2,3,4,5,6,7])
print(np.max(var))

7


ARGMAX/ARGMIN

In [12]:
var2=np.array([1,2,3,4,5,1,1])
print(np.argmax(var2))

4


In [14]:
var=np.array([1,2,3,4,5,1,1])
print("min:",np.min(var),np.argmin(var))
print("max:",np.max(var),np.argmax(var))

min: 1 0
max: 5 4


In [16]:
var=np.array([[1,2,3],[4,5,1]])
print(np.min(var,axis=0))       #axis=0 ;column
print(np.max(var,axis=1)) #axis=1 ; row

[1 2 1]
[3 5]


SQRT

In [19]:
var1=np.array([4,121,9,256])
print(np.sqrt(var1))

[ 2. 11.  3. 16.]


SIN

In [20]:
var2=np.array([1,2,3])
print(np.sin(var2))

[0.84147098 0.90929743 0.14112001]


COS

In [22]:
var3=np.array([1,2,3])
print(np.cos(var3))

[ 0.54030231 -0.41614684 -0.9899925 ]


CUMSUM

In [26]:
var4=np.array([1,2,3])
print(np.cumsum(var4))

[1 3 6]
