In [1]:
import numpy as np

Broadcasting
conditions to perform operations
-same dimension
(1x3)  (3x1) -->(3x3)

In [2]:
var1=np.array([1,2,3])
var2=np.array([1,2,3,4])
add=np.add(var1,var2)
print(add)

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [6]:
var1=np.array([1,2,3])
print(var1)
var2=np.array([[1],[2],[3]])
print(var2)
add=np.add(var1,var2)
print(add)
print(var1.shape)
print(var2.shape)
print(add.shape)

[1 2 3]
[[1]
 [2]
 [3]]
[[2 3 4]
 [3 4 5]
 [4 5 6]]
(3,)
(3, 1)
(3, 3)


In [13]:
a=np.array([[2],[3]])
print(a.shape)
b=np.array([[1,2,3],[1,2,3]])
print(b.shape)
add=np.add(a,b)
print(add)
print(add.shape)

(2, 1)
(2, 3)
[[3 4 5]
 [4 5 6]]
(2, 3)
