Indexing the numpy array

In [1]:
import numpy as np

In [5]:
var=np.array([8,35,7,90,87])
print(var)
print(var[4])


[ 8 35  7 90 87]
87


In [6]:
var=np.random.randint(3,100,9)
print(var)
print(var[7])

[ 5 86 49 27 41 48 77 43 52]
43


In [17]:
var1=np.array([[3,7,10],[8,10,11]])
print(var1)
print(var1[0,1])

[[ 3  7 10]
 [ 8 10 11]]
7


In [24]:
var1=np.array([[[3,7,10],[8,10,11],[23,32,46]],[[43,81,78],[21,13,11],[3,199,130]]])
print(var1)
print(var1.ndim)
print(var1[1,0,1])

[[[  3   7  10]
  [  8  10  11]
  [ 23  32  46]]

 [[ 43  81  78]
  [ 21  13  11]
  [  3 199 130]]]
3
81


Slicing

In [29]:
var=np.array([12,45,3,5,8,2,9])
print(var)
print("1 to 5-",var[1:5])

[12 45  3  5  8  2  9]
1 to 5- [45  3  5  8]


In [38]:
var=np.random.randint(1,100,20)
print(var)
print("5 to end:",var[5:])
print("start to 5:",var[:5])
print("5 to end:",var[5:])
print("start to end:",var[::])
print("2 step:",var[1:18:2])


[38 12 28 63 16 72 60 63  4 83 35 26 26 60 26 64 51 66 48 37]
5 to end: [72 60 63  4 83 35 26 26 60 26 64 51 66 48 37]
start to 5: [38 12 28 63 16]
5 to end: [72 60 63  4 83 35 26 26 60 26 64 51 66 48 37]
start to end: [38 12 28 63 16 72 60 63  4 83 35 26 26 60 26 64 51 66 48 37]
2 step: [12 63 72 63 83 26 60 64 66]


In [70]:
var1=np.array([[1,2,3,36,32],[4,5,6,23,41],[23,1,45,91,12]])
print(var1)
print(var1.ndim)
print(var1[0:1:4])
print(var1[0:1:3])

[[ 1  2  3 36 32]
 [ 4  5  6 23 41]
 [23  1 45 91 12]]
2
[[ 1  2  3 36 32]]
[[ 1  2  3 36 32]]
