numpy array iteration 

In [1]:
import numpy as np

In [6]:
var=np.array([2,5,6,7,8,4,9])
print(var)
print()
for i in var:
     print(var)

[2 5 6 7 8 4 9]

[2 5 6 7 8 4 9]
[2 5 6 7 8 4 9]
[2 5 6 7 8 4 9]
[2 5 6 7 8 4 9]
[2 5 6 7 8 4 9]
[2 5 6 7 8 4 9]
[2 5 6 7 8 4 9]


In [7]:
var=np.array([2,5,6,7,8,4,9])
print(var)
print()
for i in var:
     print(i)

[2 5 6 7 8 4 9]

2
5
6
7
8
4
9


In [9]:
var1=np.array([[1,2,3,4],[5,6,7,8]])
print(var1)
print()
for j in var1:
    print(j)
for k in var1:
    for l in k:
        print(l)

[[1 2 3 4]
 [5 6 7 8]]

[1 2 3 4]
[5 6 7 8]
1
2
3
4
5
6
7
8


In [10]:
var1=np.array([[[1,2,3,4],[5,6,7,8]]])
print(var1)
print(var1.ndim)
print()
for i in var1:
    for j in i:
        for k in j:
            print(k)

[[[1 2 3 4]
  [5 6 7 8]]]
3

1
2
3
4
5
6
7
8


nditer

In [15]:
var1=np.array([[[1,2,3,4],[5,6,7,8]]])
print(var1)
print(var1.ndim)
print()
for i in np.nditer(var1):
    print(i)

[[[1 2 3 4]
  [5 6 7 8]]]
3

1
2
3
4
5
6
7
8


In [22]:
var2=np.array([[[1,2,3,4],[5,6,7,8]]])
print(var2)
print(var2.ndim)
print()
for i in np.nditer(var2,flags=["buffered"],op_dtypes=["S"]):
    print(i)

[[[1 2 3 4]
  [5 6 7 8]]]
3

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
np.bytes_(b'4')
np.bytes_(b'5')
np.bytes_(b'6')
np.bytes_(b'7')
np.bytes_(b'8')


ndnumerate()

In [25]:
var2=np.array([[[1,2,3,4],[5,6,7,8]]])
print(var2)
print(var2.ndim)
print()
for i,d in np.ndenumerate(var2):
 print(i,d)

[[[1 2 3 4]
  [5 6 7 8]]]
3

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 1, 0) 5
(0, 1, 1) 6
(0, 1, 2) 7
(0, 1, 3) 8
