copy vs view

In [1]:
import numpy as np

In [9]:
var=np.array([1,2,3,4])
print(var)
print()
co=var.copy()
print("var:",var)
print("copy:",co)

var=np.array([1,2,3,4])
print(var)
print()

co=var.copy()
var[1]=40
print("var:",var)
print("copy:",co)

[1 2 3 4]

var: [1 2 3 4]
copy: [1 2 3 4]
[1 2 3 4]

var: [ 1 40  3  4]
copy: [1 2 3 4]


In [5]:
var=np.array([1,2,3,4])
print(var)
print()
view=var.view()
print("var:",var)
print("view:",view)

[1 2 3 4]

var: [1 2 3 4]
view: [1 2 3 4]


In [10]:
var=np.array([1,2,3,4])
print(var)
print()
view=var.view()
var[1]=20
print("var:",var)
print("view:",view)

[1 2 3 4]

var: [ 1 20  3  4]
view: [ 1 20  3  4]
