In [2]:
import numpy as np

In [7]:
var1=np.array([1,2,3,4,5])
var2=np.array([6,7,8,9,0])
var12=np.concatenate((var1,var2))
print(var12)

[1 2 3 4 5 6 7 8 9 0]


In [9]:
var1=np.array([[1,2,3,4,5],[12,13,14,15,16]])
var2=np.array([[21,22,23,24,25],[32,33,34,35,36]])
print(var1)
print(var2)
var12=np.concatenate((var1,var2))
print(var12)



[[ 1  2  3  4  5]
 [12 13 14 15 16]]
[[21 22 23 24 25]
 [32 33 34 35 36]]
[[ 1  2  3  4  5]
 [12 13 14 15 16]
 [21 22 23 24 25]
 [32 33 34 35 36]]


In [11]:
var1=np.array([[1,2,3,4,5],[12,13,14,15,16]])
var2=np.array([[21,22,23,24,25],[32,33,34,35,36]])
print(var1)
print(var2)
var12=np.concatenate((var1,var2),axis=1)
print(var12)

[[ 1  2  3  4  5]
 [12 13 14 15 16]]
[[21 22 23 24 25]
 [32 33 34 35 36]]
[[ 1  2  3  4  5 21 22 23 24 25]
 [12 13 14 15 16 32 33 34 35 36]]


In [12]:
var1=np.array([[1,2,3,4,5],[12,13,14,15,16]])
var2=np.array([[21,22,23,24,25],[32,33,34,35,36]])
print(var1)
print(var2)
var12=np.concatenate((var1,var2),axis=0)
print(var12)

[[ 1  2  3  4  5]
 [12 13 14 15 16]]
[[21 22 23 24 25]
 [32 33 34 35 36]]
[[ 1  2  3  4  5]
 [12 13 14 15 16]
 [21 22 23 24 25]
 [32 33 34 35 36]]


stack function

In [21]:
var1=np.array([[1,2,3,4,5],[12,13,14,15,16]])
var2=np.array([[21,22,23,24,25],[32,33,34,35,36]])
print(var1)
print()
print(var2)
var12=np.stack((var1,var2))
print()
print(var12)

[[ 1  2  3  4  5]
 [12 13 14 15 16]]

[[21 22 23 24 25]
 [32 33 34 35 36]]

[[[ 1  2  3  4  5]
  [12 13 14 15 16]]

 [[21 22 23 24 25]
  [32 33 34 35 36]]]


In [19]:
var1=np.array([[1,2],[12,13]])
var2=np.array([[21,22,],[32,33]])
print()
print(var1)
print()
print(var2)

var12=np.stack((var1,var2),axis=1)
print()
print(var12)


[[ 1  2]
 [12 13]]

[[21 22]
 [32 33]]

[[[ 1  2]
  [21 22]]

 [[12 13]
  [32 33]]]


In [27]:
var1=np.array([[1,2,3,4,5],[12,13,14,15,16]])
var2=np.array([[21,22,23,24,25],[32,33,34,35,36]])
print(var1)
print()
print(var2)
var12=np.stack((var1,var2))
var13=np.hstack((var1,var2))#row
var14=np.vstack((var1,var2))#column
var15=np.dstack((var1,var2))#height
print()
print("var12:",var12)
print("var13:",var13)
print("var14:",var14)
print(var15)

[[ 1  2  3  4  5]
 [12 13 14 15 16]]

[[21 22 23 24 25]
 [32 33 34 35 36]]

var12: [[[ 1  2  3  4  5]
  [12 13 14 15 16]]

 [[21 22 23 24 25]
  [32 33 34 35 36]]]
var13: [[ 1  2  3  4  5 21 22 23 24 25]
 [12 13 14 15 16 32 33 34 35 36]]
var14: [[ 1  2  3  4  5]
 [12 13 14 15 16]
 [21 22 23 24 25]
 [32 33 34 35 36]]
[[[ 1 21]
  [ 2 22]
  [ 3 23]
  [ 4 24]
  [ 5 25]]

 [[12 32]
  [13 33]
  [14 34]
  [15 35]
  [16 36]]]


splitting array

In [32]:
var1=np.array([1,2,3,4,5,6])
varsplit=np.array_split(var1,2)
print(varsplit)
print(var1[0])

[array([1, 2, 3]), array([4, 5, 6])]
1


In [36]:
var1=np.array([[1,2,3,4,5],[12,13,14,15,16]])
varsplit=np.array_split(var1,2)
print()
varsplit=np.array_split(var1,2,axis=1)

print(varsplit)



[array([[ 1,  2,  3],
       [12, 13, 14]]), array([[ 4,  5],
       [15, 16]])]
