In [2]:
import numpy as np

search array:search an array for a certain value,and return the indexes that get a match

In [3]:
var=np.array([1,2,4,6,8,3,2,6,17,18,16,2])
var1=np.where(var==2)
print(var1)

(array([ 1,  6, 11]),)


In [7]:
var=np.array([1,2,4,6,8,3,2,6,17,18,16,2])
var1=np.where((var%2)==0)
print(var1)

(array([ 1,  2,  3,  4,  6,  7,  9, 10, 11]),)


Search sorted array

In [9]:
var=np.array([1,2,3,4,6,7,8,9])
var1=np.searchsorted(var,5)
print(var1)

4


In [13]:
var=np.array([1,2,3,4,6,7,8,9,10,11])
var1=np.searchsorted(var,12,side="right")
print(var1)

10


In [15]:
var=np.array([1,2,3,4,6,7,8,9,10,11])
var1=np.searchsorted(var,[1,3,4])
print(var1)

[0 2 3]


sort array

In [16]:
var=np.array([1,2,3,4,6,21,43,7,89,100,7,8,9,10,11])
var1=np.sort(var)
print(var1)

[  1   2   3   4   6   7   7   8   9  10  11  21  43  89 100]


In [17]:
var=np.array(["a","c","a","z","p"])
var1=np.sort(var)
print(var1)

['a' 'a' 'c' 'p' 'z']


In [18]:
var=np.array([[1,2,3,4,6],[21,43,7,89,100],[7,8,9,10,11]])
var1=np.sort(var)
print(var1)

[[  1   2   3   4   6]
 [  7  21  43  89 100]
 [  7   8   9  10  11]]


filter array

In [20]:
var=np.array(["a","c","a","z","p"])
f=[True,False,True,False,True]
filarr=var[f]
print(filarr)

['a' 'a' 'p']
