In [1]:
import numpy as np

shuffle

In [2]:
var=np.array([1,2,3,4,5,6,7,8,9,10])
np.random.shuffle(var)
print(var)

[ 6  7  2  9 10  3  4  8  1  5]


In [3]:
var=np.array([1,2,3,4,5,6,7,8,9,10])
np.random.shuffle(var)
print(var)

[ 3  2 10  9  7  6  4  1  5  8]


unique

In [7]:
var=np.array([1,1,2,3,3,3,4,5,5,4,8,6,7,7,2,5,8,9,9,10])
x=np.unique(var,return_index=True,return_counts=True)
print(x)

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), array([ 0,  2,  3,  6,  7, 11, 12, 10, 17, 19]), array([2, 2, 3, 2, 3, 1, 2, 2, 2, 1]))


resize

In [8]:
var=np.array([1,2,34,5,6,7,8])
y=np.resize(var,(2,3))
print(y)


[[ 1  2 34]
 [ 5  6  7]]


flatten

In [9]:
var=np.array([[1,2,3,4,6],[21,43,7,89,100],[7,8,9,10,11]])
print(var)
print(var.flatten())

[[  1   2   3   4   6]
 [ 21  43   7  89 100]
 [  7   8   9  10  11]]
[  1   2   3   4   6  21  43   7  89 100   7   8   9  10  11]


In [11]:
var=np.array([[1,2,3,4,6],[21,43,7,89,100],[7,8,9,10,11]])
print(var)
print(var.flatten(order="C"))

[[  1   2   3   4   6]
 [ 21  43   7  89 100]
 [  7   8   9  10  11]]
[  1   2   3   4   6  21  43   7  89 100   7   8   9  10  11]


In [12]:
var=np.array([[1,2,3,4,6],[21,43,7,89,100],[7,8,9,10,11]])
print(var)
print(var.flatten(order="K"))

[[  1   2   3   4   6]
 [ 21  43   7  89 100]
 [  7   8   9  10  11]]
[  1   2   3   4   6  21  43   7  89 100   7   8   9  10  11]


In [14]:
var=np.array([[1,2,3,4,6],[21,43,7,89,100],[7,8,9,10,11]])
print(var)
print(var.flatten(order="F"))
print(var.flatten(order="A"))

[[  1   2   3   4   6]
 [ 21  43   7  89 100]
 [  7   8   9  10  11]]
[  1  21   7   2  43   8   3   7   9   4  89  10   6 100  11]
[  1   2   3   4   6  21  43   7  89 100   7   8   9  10  11]


In [15]:
var=np.array([[1,2,3,4,6],[21,43,7,89,100],[7,8,9,10,11]])
print(var)
print(np.ravel(var))

[[  1   2   3   4   6]
 [ 21  43   7  89 100]
 [  7   8   9  10  11]]
[  1   2   3   4   6  21  43   7  89 100   7   8   9  10  11]
