In [1]:
import numpy as np

insert

In [ ]:
var=np.array([1,2,34,5,6,7])
print(var)
x=np.insert(var,2,100)#(variable,index,value)
print(x)


[ 1  2 34  5  6  7]
[  1   2 100  34   5   6   7]


In [ ]:
var1=var=np.array([[1,2,3,4,6],[21,43,7,89,1],[7,8,9,10,11]])
x=x=np.insert(var1,(1,2),100)#(variable,index,value)
print(x)

[  1 100   2 100   3   4   6  21  43   7  89   1   7   8   9  10  11]


In [14]:
var1=var=np.array([[1,2,3,4,6],[21,43,7,89,1],[7,8,9,10,11]])
print(var1)
print()
x=x=np.insert(var1,(1,2),100,axis=0)#(variable,index,value,axis)
print(x)

[[ 1  2  3  4  6]
 [21 43  7 89  1]
 [ 7  8  9 10 11]]

[[  1   2   3   4   6]
 [100 100 100 100 100]
 [ 21  43   7  89   1]
 [100 100 100 100 100]
 [  7   8   9  10  11]]


delete

In [16]:
var=np.array([1,2,34,5,6,7])
print(var)
x=np.delete(var,2)#(variable,index)
print(x)

[ 1  2 34  5  6  7]
[1 2 5 6 7]
