In [1]:
import numpy as np


numpy-matrix

In [4]:
var1=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
var2=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print(var1,var2)
print()
print(var1*var2)
print(var1.dot(var2))

[[1 2 3]
 [4 5 6]
 [7 8 9]] [[1 2 3]
 [4 5 6]
 [7 8 9]]

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [5]:
var1=np.array([[1,2,3],[4,5,6],[7,8,9]])
var2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(var1,var2)
print()
print(var1*var2)

[[1 2 3]
 [4 5 6]
 [7 8 9]] [[1 2 3]
 [4 5 6]
 [7 8 9]]

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
