In [24]:
import numpy as np

In [25]:
var=np.matrix([[1,2,3],[4,5,6]])
print(var)

[[1 2 3]
 [4 5 6]]


Transpose

In [26]:
var=np.matrix([[1,2,3],[4,5,6]])
print(var)
print()
print(np.transpose(var))

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]


Swapaxes

In [41]:
var1=np.matrix([[1,2,3],[4,5,6]])
print(var1)
print()
print(np.swapaxes(var1,0,1))

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]


In [44]:
var2=np.matrix([[4,5],[7,8]])
print(var2)
print()
print(np.swapaxes(var2,0,1,))

[[4 5]
 [7 8]]

[[4 7]
 [5 8]]


Inverse

In [49]:
var3=np.matrix([[4,5],[7,8]])
print(var3)
print()
x=print(np.linalg.inv(var3))


[[4 5]
 [7 8]]

[[-2.66666667  1.66666667]
 [ 2.33333333 -1.33333333]]


power #np.linalg.matrix_power(var,n)

In [51]:
var4=np.matrix([[4,5],[7,8]])
print(var4)
print()
print(np.linalg.matrix_power(var4,3))

[[4 5]
 [7 8]]

[[ 624  735]
 [1029 1212]]


In [52]:
var4=np.matrix([[4,5],[7,8]])
print(var4)
print()
print(np.linalg.matrix_power(var4,0))

[[4 5]
 [7 8]]

[[1 0]
 [0 1]]


In [53]:
var4=np.matrix([[4,5],[7,8]])
print(var4)
print()
print(np.linalg.matrix_power(var4,-1))

[[4 5]
 [7 8]]

[[-2.66666667  1.66666667]
 [ 2.33333333 -1.33333333]]


determinate

In [54]:
var4=np.matrix([[4,5],[7,8]])
print(var4)
print()
print(np.linalg.det(var4))

[[4 5]
 [7 8]]

-3.0000000000000018
